name: Nexus
favicon: null
layout_spectrum: 0.1782
typography_spectrum: 0.3647715514525771
title: 'The Academic Musings of Mr. Gallifant '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a2038'
    - '#403c53'
    - '#63668f'
    - '#9fa3d4'
    - '#d7d8f5'
  brandStrength: 0.8242659193929285
  lightness: 0.5897583060432225
  saturation: 0.45888367015868425
  rhythmicContrast: 0.7247237795963883
purpose: []
